version: "3.8"

services:
  # Our NestJS Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: development
    volumes:
      - ./backend:/src/app
      - /src/app/node_modules/
    command: npm run start
  
    ports:
      - 3000:3000
  
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/frontend/src/app
      - /frontend/src/app/node_modules
    ports:
      - 4200:4200
    depends_on:
      - api

